# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js (v12.x)
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm install -g firebase-tools
        npm ci
        cd functions && npm ci && cd ../
    - name: Lint files
      run: npm run func-lint
    - name: Build the node project
      run: npm run build --if-present
    - name: Start the functions emulator
      run: |
        npm run func-compile
        firebase serve --only functions & npx wait-on http://localhost:5000
    - name: Start development server
      run: npm start & npx wait-on http://localhost:3000
    - name: Run tests
      run: npm test
