# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js (v14.x)
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm install -g firebase-tools
        npm install -g sass
        npm ci
        cd functions && npm ci && cd ../
    - name: Lint files
      run: |
        npm run func-compile
    - name: Build the node project
      run: npm run build --if-present
    - name: Run tests
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
        REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
      run: |
        npm run test:ci
    #- name: Upload screenshot
    #  if: always()
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: screenshot
    #    path: ./screenshot.png
    #- name: Logout of Firebase
    #  if: always()
    #  run: firebase logout --token "$FIREBASE_TOKEN"
